= mp3 tag with name file

I recently downloaded with torrent the Bob Marley\'s discography and there is all metadata in the name file but not the mp3 file. My goal is to parse name file for tagging the mp3 files.

== Reasoning for ruilding my script

=== 1. Find a language

For this type of use (files manipulation), bash script is a good way.

=== 2. Collect data

=== 2.1 scanf

I know `scanf` from C language. You give a patter to `scanf` and he collectes data. I search something like scanf for bash script.

I found on https://www.reddit.com/r/bash/comments/gxygww/why_isnt_there_scanf_or_equivalent_in_bash/[reddit] an example.

[source, bash]
----
#!/bin/bash

pattern="Fan: (.+) rpm CPU die temperature: (.+) C"
if [[ "Fan: fann rpm CPU die temperature: 42 C" =~ $pattern ]]; then
    fan=${BASH_REMATCH[1]}
    cpu=${BASH_REMATCH[2]}
fi
echo "$fan" "$cpu"
----

[quote]
I use https://www.shellcheck.net/[shellcheck] for get good practices for creating shell scripts.

=== 2.2 A loop for each files

I need a loop for each files. I found an exmample on https://w3guides.com/tutorial/bash-for-each-file-in-folder#bash-for-each-file-in-folder[w3guides.com]

[source, bash]
----
#!/bin/bash

for filename in ./*; do
	echo "${filename}"
done
----

=== 2.3 Parse the filename

For each tracks in an album, we have to collect:

* Title
* Track number

We already have:

* Artist
* Album
* Year

Example of filename for `Keep On Skanking`:
[source]
----
01 - All In One.mp3
02 - Keep On Moving.mp3
03 - Keep On Skanking.mp3
04 - Shocks Of Mighty (Soul Almighty Ve.mp3
05 - Brand New Second Hand.mp3
06 - Jungle Dub.mp3
07 - Satisfy My Soul Babe (Version).mp3
08 - Dracula (Version).mp3
09 - Vs. Lee Scratch Perry Dreamland (Featuring Bunny Wailer).mp3
10 - Comma Comma.mp3
----

=== 2.4 awk

After research I refind this dark tool. I had choosen to never learn to use this, because it's a very hard tool.

[source,man]
----
NAME
       awk — pattern scanning and processing language
----

==== 2.4.1 Print the track number

For each `.mp3` files:

[source, bash]
----
#!/bin/bash

for filename in ./\.*mp3; do
	echo "${filename}"
	echo "${filename}" | awk '{printf "Track number: %d\n", substr($1, 3)}'
done

# OUTPUT:
# ./01 - All In One.mp3
# Track number: 1
----

If I take this filename as example `./01 - All In One.mp3`. The first element is `./01`. I have to do a substring, so begin my substring to the third character.

[quote]
I find it weird, this time the index start with 1 and not 0.

With the substring I get `01` instead of `./01`. And then I use `%d` of `printf` for convert to a number.

== Other

=== Pattern matching

1. Use the bash shell
2. Enable the `extglob`
[source,bash]
----
shopt -s extglob
----

[start=3]
3. Try to list all but not mp3 files with
[source,bash]
----
ls !(*.mp3)
----
